import { CATEGORY_HINTS, WORD_CATALOG, type WordEntry } from "./dictionary";

// Published schedule input: keep this version immutable. Future expansions need
// a new catalog version and activation date so saved challenges keep their answer.
type RelatedWords = readonly [string, string, string, string, string];
const additions: Record<string, RelatedWords[]> = {
  comidas: [
    ["abacate", "fruta", "caroço", "polpa", "vitamina"],
    ["goiaba", "fruta", "doce", "semente", "pomar"],
    ["mamão", "fruta", "polpa", "semente", "vitamina"],
    ["pera", "fruta", "pomar", "casca", "doce"],
    ["pêssego", "fruta", "caroço", "pomar", "compota"],
    ["ameixa", "fruta", "caroço", "compota", "pomar"],
    ["cereja", "fruta", "caroço", "vermelho", "sobremesa"],
    ["maracujá", "fruta", "suco", "azedo", "semente"],
    ["jabuticaba", "fruta", "casca", "árvore", "geleia"],
    ["tangerina", "mexerica", "cítrico", "gomo", "fruta"],
    ["milho", "espiga", "grão", "pipoca", "plantação"],
    ["mandioca", "aipim", "raiz", "farinha", "tapioca"],
    ["abóbora", "legume", "semente", "casca", "horta"],
    ["pepino", "hortaliça", "salada", "verde", "horta"],
    ["alface", "verdura", "folha", "salada", "horta"],
    ["brócolis", "hortaliça", "couve", "verde", "salada"],
    ["espinafre", "verdura", "folha", "horta", "salada"],
    ["ervilha", "leguminosa", "vagem", "grão", "sopa"],
    ["lentilha", "leguminosa", "grão", "caldo", "refeição"],
    ["amendoim", "leguminosa", "paçoca", "casca", "petisco"],
    ["abacaxi", "fruta", "suco", "casca", "doce"],
    ["banana", "fruta", "cacho", "vitamina", "doce"],
    ["laranja", "cítrico", "fruta", "suco", "pomar"],
    ["morango", "fruta", "geleia", "vermelho", "sobremesa"],
    ["melancia", "fruta", "semente", "fatia", "verão"],
    ["uva", "vinho", "cacho", "fruta", "pomar"],
    ["limão", "cítrico", "azedo", "fruta", "suco"],
    ["manga", "fruta", "caroço", "pomar", "suco"],
    ["coco", "coqueiro", "fruta", "água", "praia"],
    ["maçã", "fruta", "pomar", "torta", "semente"],
    ["arroz", "grão", "feijão", "panela", "almoço"],
    ["feijão", "leguminosa", "grão", "caldo", "arroz"],
    ["pão", "padaria", "farinha", "fermento", "lanche"],
    ["queijo", "leite", "laticínio", "coalho", "lanche"],
    ["manteiga", "creme", "leite", "gordura", "pão"],
    ["café", "grão", "xícara", "bebida", "manhã"],
    ["chá", "infusão", "erva", "xícara", "bebida"],
    ["mel", "abelha", "colmeia", "doce", "flor"],
    ["pipoca", "milho", "panela", "cinema", "lanche"],
    ["sorvete", "gelado", "sobremesa", "casquinha", "verão"],
    ["bolo", "confeitaria", "massa", "aniversário", "festa"],
    ["biscoito", "bolacha", "forno", "farinha", "lanche"],
    ["macarrão", "massa", "molho", "prato", "almoço"],
    ["sopa", "caldo", "legume", "panela", "jantar"],
    ["salada", "verdura", "alface", "tomate", "refeição"],
    ["cenoura", "raiz", "legume", "horta", "salada"],
    ["batata", "tubérculo", "purê", "fritura", "legume"],
    ["tomate", "molho", "fruto", "salada", "horta"],
    ["cebola", "tempero", "bulbo", "cozinha", "horta"],
    ["pimenta", "picante", "tempero", "molho", "comida"],
  ],
  natureza: [
    ["cachorro", "cão", "latido", "canil", "animal"],
    ["gato", "felino", "miado", "bigode", "animal"],
    ["cavalo", "égua", "crina", "galope", "fazenda"],
    ["coelho", "lebre", "toca", "orelha", "animal"],
    ["urso", "mamífero", "hibernação", "pelagem", "floresta"],
    ["leão", "felino", "juba", "rugido", "savana"],
    ["tigre", "felino", "listra", "predador", "selva"],
    ["elefante", "tromba", "marfim", "mamífero", "savana"],
    ["girafa", "pescoço", "mamífero", "altura", "savana"],
    ["zebra", "listra", "equino", "manada", "savana"],
    ["macaco", "primata", "símio", "árvore", "floresta"],
    ["pinguim", "ave", "gelo", "nado", "frio"],
    ["papagaio", "ave", "bico", "pena", "canto"],
    ["pavão", "ave", "cauda", "pena", "cor"],
    ["flamingo", "ave", "rosa", "lago", "pena"],
    ["sapo", "anfíbio", "coaxo", "lagoa", "salto"],
    ["cobra", "serpente", "réptil", "escama", "veneno"],
    ["lagarto", "réptil", "escama", "cauda", "sol"],
    ["jacaré", "réptil", "crocodilo", "rio", "predador"],
    ["polvo", "molusco", "tentáculo", "oceano", "mar"],
    ["caranguejo", "crustáceo", "pinça", "mangue", "mar"],
    ["lagosta", "crustáceo", "carapaça", "oceano", "mar"],
    ["camarão", "crustáceo", "pesca", "mar", "água"],
    ["ouriço", "espinho", "mamífero", "proteção", "animal"],
    ["esquilo", "roedor", "noz", "árvore", "cauda"],
    ["árvore", "tronco", "galho", "folha", "floresta"],
    ["flor", "pétala", "buquê", "perfume", "jardim"],
    ["folha", "folhagem", "árvore", "verde", "outono"],
    ["raiz", "planta", "solo", "árvore", "terra"],
    ["semente", "germinação", "plantio", "fruto", "terra"],
    ["rio", "correnteza", "nascente", "água", "ponte"],
    ["lago", "lagoa", "água", "margem", "peixe"],
    ["cachoeira", "cascata", "queda", "rio", "água"],
    ["vento", "brisa", "ventania", "ar", "clima"],
    ["nuvem", "nebulosidade", "céu", "chuva", "vapor"],
    ["neve", "floco", "gelo", "inverno", "frio"],
    ["gelo", "congelamento", "neve", "água", "frio"],
    ["trovão", "trovoada", "relâmpago", "tempestade", "barulho"],
    ["relâmpago", "raio", "trovão", "tempestade", "luz"],
    ["areia", "duna", "praia", "grão", "deserto"],
    ["pedra", "rocha", "mineral", "cascalho", "solo"],
    ["cristal", "quartzo", "mineral", "brilho", "pedra"],
    ["concha", "molusco", "caracol", "praia", "mar"],
    ["coral", "recife", "oceano", "mar", "mergulho"],
    ["abelha", "colmeia", "mel", "pólen", "inseto"],
    ["formiga", "formigueiro", "inseto", "colônia", "terra"],
    ["grilo", "inseto", "salto", "canto", "noite"],
    ["tartaruga", "casco", "réptil", "mar", "praia"],
    ["golfinho", "mamífero", "baleia", "mar", "nado"],
    ["baleia", "cetáceo", "mamífero", "oceano", "gigante"],
    ["tubarão", "peixe", "predador", "barbatana", "mar"],
    ["coruja", "ave", "noturno", "pena", "floresta"],
    ["águia", "ave", "rapina", "asa", "voo"],
    ["lobo", "alcateia", "uivo", "predador", "floresta"],
    ["raposa", "canídeo", "mamífero", "cauda", "floresta"],
  ],
  objetos: [
    ["bicicleta", "pedal", "ciclista", "roda", "passeio"],
    ["carro", "automóvel", "volante", "motor", "estrada"],
    ["ônibus", "transporte", "passageiro", "motorista", "cidade"],
    ["avião", "aeronave", "piloto", "asa", "viagem"],
    ["barco", "embarcação", "remo", "vela", "água"],
    ["navio", "embarcação", "cruzeiro", "porto", "mar"],
    ["helicóptero", "aeronave", "hélice", "piloto", "voo"],
    ["motocicleta", "moto", "guidão", "motor", "estrada"],
    ["patins", "rodinha", "patinação", "calçado", "equilíbrio"],
    ["capacete", "proteção", "cabeça", "motocicleta", "segurança"],
    ["bola", "esfera", "futebol", "jogo", "esporte"],
    ["raquete", "tênis", "corda", "bola", "esporte"],
    ["rede", "malha", "pesca", "balanço", "descanso"],
    ["barraca", "tenda", "acampamento", "abrigo", "aventura"],
    ["binóculo", "lente", "observação", "distância", "visão"],
    ["câmera", "fotografia", "lente", "imagem", "registro"],
    ["telefone", "ligação", "chamada", "comunicação", "voz"],
    ["computador", "informática", "processador", "teclado", "tela"],
    ["teclado", "tecla", "digitação", "computador", "letra"],
    ["controle", "comando", "botão", "jogo", "televisão"],
    ["chave", "fechadura", "cadeado", "porta", "metal"],
    ["cadeira", "assento", "encosto", "móvel", "mesa"],
    ["mesa", "móvel", "tampo", "cadeira", "refeição"],
    ["sofá", "poltrona", "assento", "almofada", "sala"],
    ["cama", "colchão", "travesseiro", "quarto", "sono"],
    ["travesseiro", "almofada", "fronha", "cama", "sono"],
    ["cobertor", "manta", "cama", "agasalho", "frio"],
    ["tapete", "carpete", "tecido", "chão", "sala"],
    ["cortina", "persiana", "tecido", "janela", "sombra"],
    ["lâmpada", "iluminação", "luz", "energia", "teto"],
    ["lanterna", "iluminação", "pilha", "luz", "escuro"],
    ["vela", "pavio", "cera", "chama", "luz"],
    ["garrafa", "frasco", "recipiente", "tampa", "bebida"],
    ["copo", "taça", "recipiente", "vidro", "bebida"],
    ["xícara", "caneca", "pires", "café", "louça"],
    ["prato", "louça", "refeição", "comida", "mesa"],
    ["colher", "talher", "sopa", "concha", "cozinha"],
    ["garfo", "talher", "faca", "prato", "refeição"],
    ["panela", "caçarola", "tampa", "fogão", "cozinha"],
    ["tesoura", "corte", "lâmina", "papel", "costura"],
    ["agulha", "costura", "linha", "tecido", "ponta"],
    ["martelo", "ferramenta", "prego", "obra", "metal"],
    ["escada", "degrau", "subida", "altura", "andar"],
    ["mochila", "bolsa", "bagagem", "escola", "viagem"],
    ["mala", "bagagem", "viagem", "roupa", "aeroporto"],
    ["sapato", "calçado", "sola", "pé", "caminhada"],
    ["chapéu", "boné", "aba", "cabeça", "sol"],
    ["óculos", "lente", "armação", "visão", "olho"],
    ["anel", "aliança", "joia", "dedo", "ouro"],
    ["pulseira", "bracelete", "joia", "pulso", "enfeite"],
  ],
  lugares: [
    ["aquário", "peixe", "tanque", "vidro", "água"],
    ["zoológico", "animal", "recinto", "conservação", "visita"],
    ["estádio", "arquibancada", "torcida", "campo", "esporte"],
    ["piscina", "natação", "mergulho", "água", "lazer"],
    ["academia", "ginástica", "treino", "exercício", "saúde"],
    ["oficina", "conserto", "mecânico", "ferramenta", "trabalho"],
    ["fábrica", "indústria", "produção", "máquina", "produto"],
    ["laboratório", "experimento", "ciência", "pesquisa", "análise"],
    ["observatório", "astronomia", "telescópio", "céu", "pesquisa"],
    ["planetário", "astronomia", "projeção", "estrela", "ciência"],
    ["cidade", "município", "bairro", "rua", "prédio"],
    ["vila", "povoado", "aldeia", "moradia", "rua"],
    ["rua", "avenida", "calçada", "trânsito", "cidade"],
    ["ponte", "travessia", "viaduto", "rio", "estrada"],
    ["praça", "parque", "banco", "jardim", "cidade"],
    ["parque", "jardim", "lazer", "árvore", "passeio"],
    ["escola", "colégio", "aula", "aluno", "professor"],
    ["hospital", "clínica", "médico", "saúde", "cuidado"],
    ["mercado", "comércio", "compra", "produto", "feira"],
    ["padaria", "pão", "padeiro", "forno", "café"],
    ["restaurante", "refeição", "cardápio", "garçom", "cozinha"],
    ["aeroporto", "avião", "embarque", "pista", "viagem"],
    ["porto", "navio", "cais", "barco", "mar"],
    ["estação", "trem", "plataforma", "passageiro", "viagem"],
    ["fazenda", "sítio", "plantação", "gado", "campo"],
    ["celeiro", "depósito", "grão", "fazenda", "colheita"],
    ["moinho", "moagem", "farinha", "vento", "campo"],
    ["torre", "edifício", "altura", "castelo", "construção"],
    ["palácio", "castelo", "realeza", "rei", "salão"],
    ["templo", "santuário", "religião", "oração", "silêncio"],
  ],
  arte: [
    ["violino", "arco", "corda", "orquestra", "música"],
    ["sanfona", "acordeão", "fole", "instrumento", "música"],
    ["trompete", "sopro", "metal", "instrumento", "música"],
    ["harpa", "corda", "instrumento", "melodia", "música"],
    ["microfone", "voz", "amplificação", "canto", "som"],
    ["palco", "cenário", "teatro", "artista", "plateia"],
    ["fantasia", "imaginação", "disfarce", "personagem", "festa"],
    ["máscara", "disfarce", "rosto", "teatro", "fantasia"],
    ["mosaico", "azulejo", "fragmento", "imagem", "arte"],
    ["origami", "dobradura", "papel", "figura", "arte"],
    ["livro", "leitura", "página", "autor", "biblioteca"],
    ["caderno", "anotação", "folha", "escrita", "escola"],
    ["lápis", "grafite", "desenho", "escrita", "papel"],
    ["caneta", "tinta", "escrita", "assinatura", "papel"],
    ["pincel", "pintura", "tinta", "cerda", "artista"],
    ["escultura", "estátua", "argila", "artista", "museu"],
    ["desenho", "ilustração", "traço", "lápis", "papel"],
    ["dança", "coreografia", "bailarino", "ritmo", "música"],
    ["teatro", "palco", "ator", "peça", "plateia"],
    ["circo", "picadeiro", "palhaço", "acrobata", "espetáculo"],
    ["violão", "corda", "guitarra", "instrumento", "música"],
    ["piano", "tecla", "instrumento", "melodia", "música"],
    ["flauta", "sopro", "instrumento", "melodia", "música"],
    ["tambor", "percussão", "batida", "ritmo", "música"],
    ["melodia", "harmonia", "nota", "canção", "música"],
  ],
  ideias: [
    ["criatividade", "imaginação", "invenção", "ideia", "arte"],
    ["sabedoria", "conhecimento", "experiência", "aprendizado", "reflexão"],
    ["gentileza", "cortesia", "bondade", "educação", "cuidado"],
    ["gratidão", "agradecimento", "reconhecimento", "afeto", "gesto"],
    ["surpresa", "espanto", "inesperado", "novidade", "emoção"],
    ["medo", "temor", "receio", "perigo", "emoção"],
    ["calma", "tranquilidade", "serenidade", "paz", "silêncio"],
    ["orgulho", "satisfação", "conquista", "dignidade", "sentimento"],
    ["solidariedade", "cooperação", "ajuda", "união", "apoio"],
    ["justiça", "equidade", "direito", "lei", "igualdade"],
    ["amizade", "amigo", "companheirismo", "confiança", "afeto"],
    ["alegria", "felicidade", "sorriso", "contentamento", "festa"],
    ["saudade", "lembrança", "ausência", "nostalgia", "afeto"],
    ["esperança", "expectativa", "otimismo", "futuro", "desejo"],
    ["coragem", "bravura", "ousadia", "medo", "aventura"],
    ["paciência", "calma", "espera", "tolerância", "tempo"],
    ["curiosidade", "interesse", "pergunta", "descoberta", "pesquisa"],
    ["liberdade", "autonomia", "independência", "escolha", "direito"],
    ["respeito", "consideração", "dignidade", "educação", "convívio"],
    ["confiança", "segurança", "certeza", "crença", "amizade"],
    ["equilíbrio", "estabilidade", "balança", "harmonia", "peso"],
    ["vitória", "triunfo", "conquista", "campeão", "disputa"],
    ["desafio", "dificuldade", "obstáculo", "superação", "jogo"],
    ["escolha", "decisão", "opção", "alternativa", "caminho"],
    ["destino", "futuro", "sorte", "caminho", "viagem"],
  ],
  espaço: [
    ["constelação", "estrela", "astronomia", "céu", "desenho"],
    ["eclipse", "sombra", "lua", "sol", "alinhamento"],
    ["gravidade", "atração", "massa", "queda", "planeta"],
    ["nebulosa", "nuvem", "gás", "estrela", "espaço"],
    ["cratera", "impacto", "meteorito", "lua", "superfície"],
    ["lua", "satélite", "lunar", "noite", "céu"],
    ["sol", "estrela", "solar", "calor", "dia"],
    ["galáxia", "constelação", "estrela", "universo", "espaço"],
    ["universo", "cosmo", "galáxia", "espaço", "infinito"],
    ["meteoro", "meteorito", "asteroide", "céu", "luz"],
    ["asteroide", "rocha", "órbita", "planeta", "espaço"],
    ["foguete", "propulsão", "lançamento", "astronauta", "espaço"],
    ["astronauta", "cosmonauta", "nave", "missão", "espaço"],
    ["telescópio", "luneta", "lente", "astronomia", "observação"],
    ["órbita", "trajetória", "gravidade", "satélite", "planeta"],
  ],
};

export const DAILY_CATALOG_V2: readonly WordEntry[] = [
  ...WORD_CATALOG,
  ...Object.entries(additions).flatMap(([category, entries]) =>
    entries.map(([word, ...related]) => ({
      word,
      category,
      prompt: CATEGORY_HINTS[category],
      aliases: Object.fromEntries([
        [word, 1],
        ...related.map((alias, index) => [alias, [5, 10, 16, 22][index]]),
      ]),
    })),
  ),
];
