import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { gzipSync } from "node:zlib";
import pt from "dictionary-pt";
import nspell from "nspell";

const output = new URL("../server/game/generated/pt-br.ts", import.meta.url);
const signature = createHash("sha256").update(pt.aff).update(pt.dic)
  .update(await readFile(new URL(import.meta.url))).digest("hex");
const header = "// Generated by scripts/build-lexicon.mjs; source: dictionary-pt 4.0.0 (VERO).\n// " + signature + "\n";
try {
  if ((await readFile(output, "utf8")).startsWith(header)) {
    console.log("Portuguese lexicon is up to date.");
    process.exit(0);
  }
} catch (error) {
  if (error.code !== "ENOENT") throw error;
}

// nspell expands affixes eagerly. Use bounded batches to avoid holding millions
// of inflected/hyphenated forms in memory at once. Pin its version because data
// is an internal expanded-word index; correct() still checks each accepted form.
const lines = pt.dic.toString().split(/\r?\n/).slice(1).filter(Boolean);
const words = new Set();
for (let offset = 0; offset < lines.length; offset += 1000) {
  const batch = lines.slice(offset, offset + 1000);
  const spell = nspell(pt.aff, batch.length + "\n" + batch.join("\n"));
  for (const word of Object.keys(spell.data)) {
    const normalized = word.toLocaleLowerCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    if (/^[a-z]{1,80}$/.test(normalized) && spell.correct(word)) words.add(normalized);
  }
  if (offset % 50000 === 0) console.log("Expanding Portuguese lexicon: " + offset + "/" + lines.length);
}
if (words.size < 100000) throw new Error("Portuguese lexicon unexpectedly incomplete");
const compressed = gzipSync([...words].sort().join("\n"), { level: 9 }).toString("base64");
await mkdir(new URL("../server/game/generated/", import.meta.url), { recursive: true });
await writeFile(output, header + "export default " + JSON.stringify(compressed) + ";\n");
console.log("Portuguese lexicon: " + words.size + " forms, " + Math.round(compressed.length / 1024) + " KiB bundled.");
